---
title: "02.5 - Seasonal Subseries"
format: gfm
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(paged.print = FALSE)
```

```{r message=FALSE}
library(fpp3)
```

An alternative plot that emphasises the seasonal patterns is where the data for each season are collected together in separate mini time plots.


```{r}
a10 <- PBS |>
  filter(ATC2 == "A10") |>
  select(Month, Concession, Type, Cost) |>
  summarise(TotalC = sum(Cost)) |>
  mutate(Cost = TotalC / 1e6)
a10
```


```{r}
a10 |>
  gg_subseries(Cost) + 
  labs(y="$ million", title = "Subseries plot: antidiabetic drug sales")
```

The blue horizontal lines indicate the means for each month.

## Example: Australian holiday tourism

```{r}
holidays <- tourism |>
  filter(Purpose == "Holiday") |>
  group_by(State) |>
  summarise(Trips = sum(Trips))
holidays
```

```{r}
autoplot(holidays, Trips) +
  labs(y = "Overnight trips ('000)",
       title = "Australian domestic holidays")
  
```

```{r fig.height=14, fig.width=7}
gg_season(holidays, Trips) +
  labs(y = "Overnight Trips ('000)",
       title = "Australian domestic holidays")
```

```{r fig.height=12, fig.width=8}
holidays |>
  gg_subseries(Trips) +
  labs(y = "Overnight trips ('000)",
       title = "Australian domestic holidays")
```

